language: node_js

node_js:
  - "5.1"

branches:
  only:
  - develop

notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yum update
  - yum install node
  - npm install
  - npm install -g gulp
  - npm install -g protractor
  - ./node_modules/selenium-standalone/bin/selenium-standalone install
  - gulp e2e

env:
  - CEDAR_HOST=staging.metadatacenter.net CEDAR_PROFILE=server CEDAR_ANALYTICS_KEY=false CEDAR_SELENIUM_SERVER_JAR=2.50.1-server.jar CEDAR_CHROME_DRIVER=2.21-x64-chromedriver
